name: ParkBite
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  battery_plus: ^6.0.1
  connectivity_plus: ^6.0.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  sensors_plus: ^5.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/food_and_drink.json
  - assets/rides.json
  - assets/images/
  - assets/images/burger.png

  fonts:
    - family: Mario
      fonts:
        - asset: assets/fonts/Mario-Kart-DS.ttf
