// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWWIIyi4XpG0ahbrgez5U2KFVLGSeISA',
    appId: '1:499517203874:web:341205035b4a90a9227efb',
    messagingSenderId: '499517203874',
    projectId: 'roberts-rodeo',
    authDomain: 'roberts-rodeo.firebaseapp.com',
    storageBucket: 'roberts-rodeo.appspot.com',
    measurementId: 'G-BNWQTE227P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKZuQCzMkDpCEYoQ78eqWAmEIlwv1o9PQ',
    appId: '1:499517203874:android:6cdb9a2b329ccee6227efb',
    messagingSenderId: '499517203874',
    projectId: 'roberts-rodeo',
    storageBucket: 'roberts-rodeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgm8UxVwiUJTSxa1-DgUfFWoTl_yQYvCg',
    appId: '1:499517203874:ios:553da87b21bac3fa227efb',
    messagingSenderId: '499517203874',
    projectId: 'roberts-rodeo',
    storageBucket: 'roberts-rodeo.appspot.com',
    iosBundleId: 'com.example.robertsRodeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgm8UxVwiUJTSxa1-DgUfFWoTl_yQYvCg',
    appId: '1:499517203874:ios:553da87b21bac3fa227efb',
    messagingSenderId: '499517203874',
    projectId: 'roberts-rodeo',
    storageBucket: 'roberts-rodeo.appspot.com',
    iosBundleId: 'com.example.robertsRodeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWWIIyi4XpG0ahbrgez5U2KFVLGSeISA',
    appId: '1:499517203874:web:1c07a6a846e0e82d227efb',
    messagingSenderId: '499517203874',
    projectId: 'roberts-rodeo',
    authDomain: 'roberts-rodeo.firebaseapp.com',
    storageBucket: 'roberts-rodeo.appspot.com',
    measurementId: 'G-VZ17NR4Y6S',
  );

}